# Generated by Django 3.2.6 on 2021-09-04 06:44

from django.db import migrations, models
import weblog_teacher_helper.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('resume_file', models.FileField(max_length=1000, upload_to=weblog_teacher_helper.models.upload_resume_path, verbose_name=' رزومه')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال رزومه')),
                ('is_read', models.BooleanField(default=False, verbose_name='بررسی شده / نشده')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست های انتخاب به عنوان کمک استاد',
                'ordering': ['-created_on'],
            },
        ),
    ]
