# Generated by Django 3.2.6 on 2021-09-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_content', models.TextField(blank=True, null=True, verbose_name='متن نمایش زیرنویس سایت')),
                ('publication_content', models.TextField(blank=True, null=True, verbose_name='متن صفحه انتشارات')),
                ('research_content', models.TextField(blank=True, null=True, verbose_name='متن صفحه تحقیقات')),
                ('research_grants_content', models.TextField(blank=True, null=True, verbose_name='متن صفحه انتشارات بخش کمک هزینه های تحقیقاتی')),
                ('research_partner_content', models.TextField(blank=True, null=True, verbose_name='متن صفحه انتشارات بخش همکاران تحقیقاتی')),
                ('students_content', models.TextField(blank=True, null=True, verbose_name='متن صفحه دانش اموزان')),
                ('teaching_content', models.TextField(blank=True, null=True, verbose_name='متن صفحه آموزش')),
                ('blogs_content', models.TextField(blank=True, null=True, verbose_name='متن صفحه مقالات')),
                ('blogs_notification_content', models.TextField(blank=True, null=True, verbose_name='متن اطلاعیه صفحه مقالات')),
                ('contact_content', models.TextField(blank=True, null=True, verbose_name='متن صفحه ارتباط')),
            ],
            options={
                'verbose_name': 'متن',
                'verbose_name_plural': 'متن های سایت',
            },
        ),
    ]
