# Generated by Django 3.2.6 on 2021-09-04 08:18

from django.db import migrations, models
import django.db.models.deletion
import weblog_blogs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weblog_blogs_category', '0001_initial'),
        ('weblog_blogs_Tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مفاله')),
                ('writer', models.CharField(max_length=150, verbose_name='نویسنده مقاله')),
                ('short_description', models.CharField(max_length=150, verbose_name='توضیح کوتاه')),
                ('publish_date', models.DateField(verbose_name='تاریخ انتشار مقاله')),
                ('cover', models.ImageField(upload_to=weblog_blogs.models.upload_image_path, verbose_name='کاور مقاله')),
                ('content_1', models.TextField(blank=True, null=True, verbose_name='متن مقاله قبل تصویر')),
                ('image', models.ImageField(blank=True, null=True, upload_to=weblog_blogs.models.upload_image_path, verbose_name='تصویر برای مقاله')),
                ('image_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیح کوتاه تصویر')),
                ('content_2', models.TextField(blank=True, null=True, verbose_name='متن مقاله بعد تصویر')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='عنوان در url')),
                ('count_comment', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعدا کامنت ها')),
                ('writer_image', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='تصویر نویسنده')),
                ('categories', models.ManyToManyField(blank=True, to='weblog_blogs_category.Categories', verbose_name=' دسته بندی ها ')),
                ('tags', models.ManyToManyField(blank=True, to='weblog_blogs_Tags.Tags', verbose_name='برچسب ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('body', models.TextField(verbose_name='نظر')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='weblog_blogs.blogs', verbose_name='مقالات')),
            ],
            options={
                'verbose_name': 'نظر / کامنت',
                'verbose_name_plural': 'نظرات / کامنت ها',
                'ordering': ['-created_on'],
            },
        ),
    ]
