# Generated by Django 3.2.6 on 2021-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.CharField(max_length=150, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
                ('message', models.CharField(max_length=150, verbose_name='پیغام')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده / نشده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'ordering': ['created_on'],
            },
        ),
    ]
