# Generated by Django 3.2.6 on 2021-09-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=150, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده / نشده')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ContactWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_address', models.TextField(blank=True, null=True, verbose_name='آدرس دانشگاه')),
                ('office_address', models.TextField(blank=True, null=True, verbose_name='آدرس دفتر')),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن دفتر')),
                ('internal_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن داخلی دفتر')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره همراه')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='فکس')),
                ('faceBook_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس فیس بوک')),
                ('twitter_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس توییتر')),
                ('googlePlus_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس گوگل پلاس')),
                ('linkedin_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس لینکدین')),
                ('skype_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس اسکایپ')),
                ('instagram_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس اینستاگرام')),
            ],
            options={
                'verbose_name': 'راه ارتباطی',
                'verbose_name_plural': 'راه های ارتباطی کاربران',
            },
        ),
    ]
