# Generated by Django 3.2.6 on 2021-08-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog_contact', '0003_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_address', models.TextField(blank=True, null=True, verbose_name='آدرس دانشگاه')),
                ('office_address', models.TextField(blank=True, null=True, verbose_name='آدرس دفتر')),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن دفتر')),
                ('internal_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تلفن داخلی دفتر')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره همراه')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='فکس')),
                ('faceBook_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس فیس بوک')),
                ('twitter_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس توییتر')),
                ('googlePlus_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس گوگل پلاس')),
                ('linkedin_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس لینکدین')),
                ('skype_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس اسکایپ')),
                ('instagram_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس اینستاگرام')),
            ],
            options={
                'verbose_name': 'راه ارتباطی',
                'verbose_name_plural': 'راه های ارتباطی کاربران',
            },
        ),
    ]
