# Generated by Django 3.2.6 on 2021-08-29 08:18

from django.db import migrations, models
import weblog_students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('rule', models.CharField(max_length=150, verbose_name='شغل')),
                ('image', models.ImageField(upload_to=weblog_students.models.upload_image_path, verbose_name='تصویر ')),
                ('faceBook_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس فیس بوک')),
                ('twitter_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='آدرس توییتر')),
                ('home_page', models.URLField(blank=True, max_length=150, null=True, verbose_name='آدرس سایت')),
                ('description', models.TextField(verbose_name='معرفی')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('active', models.BooleanField(default=False, verbose_name='فعال/غیر فعال')),
            ],
            options={
                'verbose_name': 'دانش جو',
                'verbose_name_plural': 'لیست دانش جویان',
                'ordering': ['-created_on'],
            },
        ),
    ]
