# Generated by Django 3.2.6 on 2021-09-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان با منحصر به فردباشد', max_length=120, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='عنوان در url')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیر فعال ')),
            ],
            options={
                'verbose_name': 'تگ/برچسب',
                'verbose_name_plural': 'تگ ها / برچست ها',
            },
        ),
    ]
