# Generated by Django 3.2.6 on 2021-09-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان درس')),
                ('content', models.CharField(max_length=500, verbose_name=' توضیحی کوتاه درباره درس')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'لیست دروس',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Teaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name=' متن مبحث آموزشی')),
            ],
            options={
                'verbose_name': 'مبحث آموزشی',
                'verbose_name_plural': 'مباحث آموزشی',
                'ordering': ['-id'],
            },
        ),
    ]
