# Generated by Django 3.2.6 on 2021-09-04 06:41

import django.core.validators
from django.db import migrations, models
import weblog_about_us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('Current_degree', models.CharField(max_length=150, verbose_name='بالاترین درجه فعلی')),
                ('current_college', models.CharField(max_length=150, verbose_name='نام دانشکده فعلی')),
                ('image', models.ImageField(upload_to=weblog_about_us.models.upload_image_path, verbose_name='تصویر خودتان')),
                ('resume', models.FileField(blank=True, null=True, upload_to=weblog_about_us.models.upload_resume_path, verbose_name='رزومه')),
                ('Introduction', models.TextField(verbose_name='معرفی')),
                ('now', models.CharField(help_text='مستر/دکتری/پست دکتری', max_length=200, verbose_name='مدارک فعلی ')),
            ],
            options={
                'verbose_name': 'معرفی',
                'verbose_name_plural': 'معرفی خودتان',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200, verbose_name='مدرک تحصیلی')),
                ('university', models.CharField(max_length=200, verbose_name='دانشگاه')),
                ('end_year', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(2021)], verbose_name='سال دریافت مدرک')),
            ],
            options={
                'verbose_name': 'مدرک تحصیلی',
                'verbose_name_plural': 'اطلاعات مدرک تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='HonorsAndAwards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='محتوی')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('link', models.URLField(blank=True, null=True, verbose_name='آدرس اینترنتی')),
            ],
            options={
                'verbose_name': 'افتخار/جایزه',
                'verbose_name_plural': 'افتخارات و جوایز',
            },
        ),
    ]
